name: spherely-dev
channels:
  - conda-forge
dependencies:
  - cxx-compiler
  - s2geometry>=0.11.1
  - libabseil
  - cmake
  - python
  - numpy
  - pybind11>=2.11.0
  - scikit-build-core
  - ninja
  - pytest
  - pip
  - geoarrow-pyarrow
